{% set name = "SPARQLWrapper" %}
{% set version = "1.8.1" %}
{% set sha256 = "da760be6f448f2030f2b4f7cecd4c55b0c2133458d5c420c50f78169db133e82" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - keepalive

test:
  imports:
    - SPARQLWrapper

about:
  home: https://github.com/RDFLib/sparqlwrapper
  license: W3C
  license_file: LICENSE.txt
  summary: 'SPARQL Endpoint interface to Python for use with rdflib'
  dev_url: https://github.com/RDFLib/sparqlwrapper
  doc_url: http://rdflib.github.io/sparqlwrapper

extra:
  recipe-maintainers:
    - satra
